"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import sys
import dj_database_url

from .env import bool_env, csv_env, int_env, optional_env, required_env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = required_env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool_env("DJANGO_DEBUG", default=False)

# Supabase stays server-side. The browser talks only to Django.
SUPABASE_URL = required_env("SUPABASE_URL")
SUPABASE_PUBLISHABLE_KEY = optional_env("SUPABASE_PUBLISHABLE_KEY")
SUPABASE_SECRET_KEY = required_env("SUPABASE_SECRET_KEY")
SUPABASE_PRIVATE_STORAGE_BUCKET = optional_env("SUPABASE_PRIVATE_STORAGE_BUCKET", default="private")
SUPABASE_SIGNED_URL_TTL_SECONDS = int_env("SUPABASE_SIGNED_URL_TTL_SECONDS", default=60)

ALLOWED_HOSTS = csv_env("DJANGO_ALLOWED_HOSTS", default="localhost,127.0.0.1")
CSRF_TRUSTED_ORIGINS = csv_env("DJANGO_CSRF_TRUSTED_ORIGINS", default="")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'usuarios.apps.UsuariosConfig',
    'clientes.apps.ClientesConfig',
    'dashboard.apps.DashboardConfig',
    'relatorios.apps.RelatoriosConfig',
    'config',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

AUTH_USER_MODEL = "usuarios.Usuario"
LOGIN_URL = "usuarios:login"
LOGIN_REDIRECT_URL = "dashboard:index"
REPORT_EXPORT_MAX_ROWS = int_env("REPORT_EXPORT_MAX_ROWS", default=10000)
LOGOUT_REDIRECT_URL = "usuarios:login"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=required_env("DATABASE_URL"),
        conn_max_age=60,
        conn_health_checks=True,
        ssl_require=True,
    )
}

ISOLATED_DATABASE_COMMANDS = {"test", "makemigrations"}
if ISOLATED_DATABASE_COMMANDS.intersection(sys.argv):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

# Production-oriented transport and cookie security.
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = bool_env("DJANGO_SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = bool_env("DJANGO_CSRF_COOKIE_SECURE", default=not DEBUG)
SECURE_SSL_REDIRECT = bool_env("DJANGO_SECURE_SSL_REDIRECT", default=not DEBUG)
if "test" in sys.argv:
    SECURE_SSL_REDIRECT = False
DJANGO_TRUST_X_FORWARDED_PROTO = bool_env(
    "DJANGO_TRUST_X_FORWARDED_PROTO",
    default=False,
)
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if DJANGO_TRUST_X_FORWARDED_PROTO
    else None
)
SECURE_HSTS_SECONDS = int_env("DJANGO_SECURE_HSTS_SECONDS", default=31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = bool_env("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=not DEBUG)
SECURE_HSTS_PRELOAD = bool_env("DJANGO_SECURE_HSTS_PRELOAD", default=False)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
PRIVATE_STORAGE_REQUEST_MAX_BYTES = int_env(
    "PRIVATE_STORAGE_REQUEST_MAX_BYTES",
    default=4096,
)

LOG_REDACTED_SECRETS = tuple(
    value
    for value in (
        SECRET_KEY,
        DATABASES["default"].get("PASSWORD"),
        SUPABASE_PUBLISHABLE_KEY,
        SUPABASE_SECRET_KEY,
    )
    if value
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "redact_secrets": {
            "()": "config.logging.SecretRedactionFilter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["redact_secrets"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

