# Generated by Django 6.0.7 on 2026-07-22 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], db_index=True, max_length=2)),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('documento', models.CharField(error_messages={'unique': 'Já existe um cliente cadastrado com este documento.'}, max_length=14, unique=True)),
                ('data_referencia', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('telefone', models.CharField(db_index=True, max_length=11)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('observacoes', models.TextField(blank=True)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], db_index=True, default='ATIVO', max_length=7)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('nome',),
                'indexes': [models.Index(fields=['estado', 'cidade'], name='clientes_estado_cidade_idx'), models.Index(fields=['tipo', 'situacao'], name='clientes_tipo_situacao_idx'), models.Index(fields=['criado_em'], name='clientes_criado_em_idx'), models.Index(fields=['atualizado_em'], name='clientes_atualizado_em_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('tipo__in', ['PF', 'PJ'])), name='clientes_tipo_valido_ck'), models.CheckConstraint(condition=models.Q(('situacao__in', ['ATIVO', 'INATIVO'])), name='clientes_situacao_valida_ck'), models.CheckConstraint(condition=models.Q(models.Q(('documento__length', 11), ('tipo', 'PF')), models.Q(('documento__length', 14), ('tipo', 'PJ')), _connector='OR'), name='clientes_documento_tipo_len_ck'), models.CheckConstraint(condition=models.Q(('telefone__length__in', (10, 11))), name='clientes_telefone_len_ck'), models.CheckConstraint(condition=models.Q(('cep__length', 8)), name='clientes_cep_len_ck')],
            },
        ),
    ]
